---
title: "EDLD_Final"
format: html
editor: visual
---

## imports

```{r}
library(rio)
library(here)
library(tidyverse)
library(ggplot2)
library(ggtext)
library(janitor)
```

Plot \# 1: Line chart

```{r}
project_data%>%
  ggplot(aes(x=year))+
  geom_point(aes(x=year, y = br_pak),color="green",size=1,shape=16)+
  geom_line(aes(y=br_pak),color="green")+
  geom_point(aes(x=year, y = br2),color="blue",size=1,shape=18)+
  geom_line(aes(y=br2),color="blue")+
  geom_point(aes(x=year, y = br3),color="orange",size=1,shape=17)+
  geom_line(aes(y=br3),color="orange")+
  theme_minimal()+
  scale_x_continuous(breaks = seq(1961,2022,by=5),
                     labels = seq(1961,2022,by=5),
                     expand = c(0,0),
                     limits = c(1961,2022))+
  labs("x=Year",
       y="Birth Rates by Country",
       title="Decreasing birthrates in South Asia",
      caption="Data from World Bank") +
  annotate(
    'text',
    x = 1966,
    y = 45,
    label = 'Pakistan',
    size = 3
  )+
annotate(
    'text',
    x = 1966,
    y = 50,
    label = 'Bangladesh',
    size = 3
  )+
annotate(
    'text',
    x = 1966,
    y = 42,
    label = 'India',
    size = 3
  )
         
         
                     
                    


```

```{r}
project_data%>%
  slice(37:62)%>%
  ggplot(aes(x=br_pak,y=gdp_pak, size = women_political_pak)) +
  geom_point(alpha = .5)+
  theme_minimal()
```

```{r}
project_data%>%
  slice(37:62)%>%
  ggplot(aes(x=br2,y=gdp_ind, size = women_india)) +
  geom_point(alpha = .5)+
  theme_minimal()
```

```{r}
project_data%>%
  slice(37:62)%>%
  ggplot(aes(x=br3,y=gdp_bangladesh, size = women_bangladesh)) +
  geom_point(alpha = .5)+
  theme_minimal()
```
